version: '3'

services:

  frontend:
    # build: ./src/frontend/
    image: gcr.io/earthworks-541/mandala-inv-frontend
    ports:
      - "80:3000"
    tty: true
    volumes:
      - ./frontend/src:/frontend/src
    networks:
      - common
    environment: 
      PROD: 1
      BACKEND_HOST: backend
    depends_on:
      - backend

  backend:
    # build: ./src/backend/
    image: gcr.io/earthworks-541/mandala-inv-backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend:/src/backend
    networks:
      - common
    environment:
      PROD: 1
      DB_HOST: database
    depends_on:
      - database

  database:
    image: "mongo"
    volumes:
      - ./data/db:/data/db
    ports: 
      - "27017:27017"  # For debugging with MongoDB Compass
    networks:
      - common

networks:
  common:
    driver: bridge